version: '3'

services:
 myapplication:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT: "5000"
   ports:
     - "5000:8080"
 db:
  image: postgres:latest
  environment:
    POSTGRES_DB: "back_end_4gd4"
    POSTGRES_USER: "back_end_4gd4_user"
    POSTGRES_PASSWORD: "AsrTpmGMGkdBkoxPfEJ7rZmD7vLxtlRb"
