version: '3'

services:
 myapplication:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT: "5000"
   ports:
     - "5000:8080"
 db:
  image: postgres:15
  environment:
    POSTGRES_DB: "back_end_1vxx"
    POSTGRES_USER: "admin"
    POSTGRES_PASSWORD: "zROLWMZmaXBWInlu4wHHV4sh11MgH3kF"
